"""
SR3 Calendar Spread Carry — Phase-2 promoted object as atomic sleeve.

Phase-2 definition (faithful port):
  ret_t = position_{t-1} * spread_return_t
  spread_return_t = R2_return_t - R1_return_t

Legs: R2 = Rank 2 (long), R1 = Rank 1 (short). SOFR futures from market.get_contracts_by_root.
Spread return = equal-notional leg return difference: w_long * r_long - w_short * r_short
with w_long=w_short=1.0 (no DV01 adjustment by default).

Source: Phase-2 harness used SR3 Calendar Carry Phase-1 from
  reports/runs/carry/sr3_calendar_carry_phase2/20251216_150004 (comparison_returns.csv column "carry")
  generated by scripts/diagnostics/run_sr3_calendar_carry_phase2.py which loads
  Phase-1 run from src/strategies/carry/sr3_calendar_carry.py compute_sr3_calendar_carry_phase1().
"""

import pandas as pd
from typing import Optional

from src.strategies.carry.sr3_calendar_carry import compute_sr3_calendar_carry_phase1


class SR3CalendarSpreadCarryReturnsAdapter:
    """
    Adapter that exposes compute_returns(market, start, end) for ExecSim
    sleeve_returns emission. Delegates to compute_sr3_calendar_carry_phase1 (Phase-2 logic).
    """

    def __init__(
        self,
        mode: str = "phase1",
        zscore_window: int = 90,
        clip: float = 2.0,
        target_vol: float = 0.10,
        vol_lookback: int = 60,
        use_dv01: bool = False,
        dv01_long: Optional[float] = None,
        dv01_short: Optional[float] = None,
        flip_sign: bool = False,
        lag: int = 1,
    ):
        self.mode = mode
        self.zscore_window = zscore_window
        self.clip = clip
        self.target_vol = target_vol
        self.vol_lookback = vol_lookback
        self.use_dv01 = use_dv01
        self.dv01_long = dv01_long
        self.dv01_short = dv01_short
        self.flip_sign = flip_sign
        self.lag = lag

    def compute_returns(
        self,
        market,
        start: str,
        end: str
    ) -> pd.Series:
        """Return daily sleeve return series for attribution (index=date)."""
        out = compute_sr3_calendar_carry_phase1(
            market=market,
            start_date=start,
            end_date=end,
            mode=self.mode,
            zscore_window=self.zscore_window,
            clip=self.clip,
            target_vol=self.target_vol,
            vol_lookback=self.vol_lookback,
            use_dv01=self.use_dv01,
            dv01_long=self.dv01_long,
            dv01_short=self.dv01_short,
            flip_sign=self.flip_sign,
            lag=self.lag,
        )
        return out["portfolio_returns"]
